//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
namespace BrainTec.NHibernateDesigner
{
	/// <summary>
	/// DomainRelationship ExampleModelHasElements
	/// Embedding relationship between the Model and Elements
	/// </summary>
	[DslDesign::DisplayNameResource("BrainTec.NHibernateDesigner.ExampleModelHasElements.DisplayName", typeof(global::BrainTec.NHibernateDesigner.NHibernateDesignerDomainModel), "BrainTec.NHibernateDesigner.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("BrainTec.NHibernateDesigner.ExampleModelHasElements.Description", typeof(global::BrainTec.NHibernateDesigner.NHibernateDesignerDomainModel), "BrainTec.NHibernateDesigner.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::BrainTec.NHibernateDesigner.NHibernateDesignerDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship(IsEmbedding=true)]
	[DslModeling::DomainObjectId("69a560a6-afa0-41e0-92f9-b79f0ea53e08")]
	public partial class ExampleModelHasElements : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// ExampleModelHasElements domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x69a560a6, 0xafa0, 0x41e0, 0x92, 0xf9, 0xb7, 0x9f, 0x0e, 0xa5, 0x3e, 0x08);
	
				
		/// <summary>
		/// Constructor
		/// Creates a ExampleModelHasElements link in the same Partition as the given ExampleModel
		/// </summary>
		/// <param name="source">ExampleModel to use as the source of the relationship.</param>
		/// <param name="target">ExampleElement to use as the target of the relationship.</param>
		public ExampleModelHasElements(ExampleModel source, ExampleElement target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(ExampleModelHasElements.ExampleModelDomainRoleId, source), new DslModeling::RoleAssignment(ExampleModelHasElements.ElementDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public ExampleModelHasElements(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public ExampleModelHasElements(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public ExampleModelHasElements(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public ExampleModelHasElements(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region ExampleModel domain role code
		
		/// <summary>
		/// ExampleModel domain role Id.
		/// </summary>
		public static readonly global::System.Guid ExampleModelDomainRoleId = new global::System.Guid(0xa392bb93, 0x462b, 0x4b92, 0xbb, 0x1e, 0xa9, 0x33, 0xa0, 0x6c, 0x3c, 0x1d);
		
		/// <summary>
		/// DomainRole ExampleModel
		/// </summary>
		[DslDesign::DisplayNameResource("BrainTec.NHibernateDesigner.ExampleModelHasElements/ExampleModel.DisplayName", typeof(global::BrainTec.NHibernateDesigner.NHibernateDesignerDomainModel), "BrainTec.NHibernateDesigner.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("BrainTec.NHibernateDesigner.ExampleModelHasElements/ExampleModel.Description", typeof(global::BrainTec.NHibernateDesigner.NHibernateDesignerDomainModel), "BrainTec.NHibernateDesigner.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "Elements", PropertyDisplayNameKey="BrainTec.NHibernateDesigner.ExampleModelHasElements/ExampleModel.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.PropagatesCopyToLinkAndOppositeRolePlayer, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("a392bb93-462b-4b92-bb1e-a933a06c3c1d")]
		public virtual ExampleModel ExampleModel
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (ExampleModel)DslModeling::DomainRoleInfo.GetRolePlayer(this, ExampleModelDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, ExampleModelDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access ExampleModel of a ExampleElement
		/// <summary>
		/// Gets ExampleModel.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static ExampleModel GetExampleModel(ExampleElement element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, ElementDomainRoleId) as ExampleModel;
		}
		
		/// <summary>
		/// Sets ExampleModel.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetExampleModel(ExampleElement element, ExampleModel newExampleModel)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, ElementDomainRoleId, newExampleModel);
		}
		#endregion
		#region Element domain role code
		
		/// <summary>
		/// Element domain role Id.
		/// </summary>
		public static readonly global::System.Guid ElementDomainRoleId = new global::System.Guid(0x35d9a097, 0x682a, 0x4799, 0xb5, 0x09, 0x1b, 0x3e, 0xa0, 0xb3, 0x91, 0xa4);
		
		/// <summary>
		/// DomainRole Element
		/// </summary>
		[DslDesign::DisplayNameResource("BrainTec.NHibernateDesigner.ExampleModelHasElements/Element.DisplayName", typeof(global::BrainTec.NHibernateDesigner.NHibernateDesignerDomainModel), "BrainTec.NHibernateDesigner.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("BrainTec.NHibernateDesigner.ExampleModelHasElements/Element.Description", typeof(global::BrainTec.NHibernateDesigner.NHibernateDesignerDomainModel), "BrainTec.NHibernateDesigner.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "ExampleModel", PropertyDisplayNameKey="BrainTec.NHibernateDesigner.ExampleModelHasElements/Element.PropertyDisplayName", PropagatesDelete = true,  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.One)]
		[DslModeling::DomainObjectId("35d9a097-682a-4799-b509-1b3ea0b391a4")]
		public virtual ExampleElement Element
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (ExampleElement)DslModeling::DomainRoleInfo.GetRolePlayer(this, ElementDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, ElementDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Elements of a ExampleModel
		/// <summary>
		/// Gets a list of Elements.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<ExampleElement> GetElements(ExampleModel element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<ExampleElement>, ExampleElement>(element, ExampleModelDomainRoleId);
		}
		#endregion
		#region ExampleModel link accessor
		/// <summary>
		/// Get the list of ExampleModelHasElements links to a ExampleModel.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::BrainTec.NHibernateDesigner.ExampleModelHasElements> GetLinksToElements ( global::BrainTec.NHibernateDesigner.ExampleModel exampleModelInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::BrainTec.NHibernateDesigner.ExampleModelHasElements>(exampleModelInstance, global::BrainTec.NHibernateDesigner.ExampleModelHasElements.ExampleModelDomainRoleId);
		}
		#endregion
		#region Element link accessor
		/// <summary>
		/// Get the ExampleModelHasElements link to a ExampleElement.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::BrainTec.NHibernateDesigner.ExampleModelHasElements GetLinkToExampleModel (global::BrainTec.NHibernateDesigner.ExampleElement elementInstance)
		{
			global::System.Collections.Generic.IList<global::BrainTec.NHibernateDesigner.ExampleModelHasElements> links = DslModeling::DomainRoleInfo.GetElementLinks<global::BrainTec.NHibernateDesigner.ExampleModelHasElements>(elementInstance, global::BrainTec.NHibernateDesigner.ExampleModelHasElements.ElementDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of Element not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region ExampleModelHasElements instance accessors
		
		/// <summary>
		/// Get any ExampleModelHasElements links between a given ExampleModel and a ExampleElement.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::BrainTec.NHibernateDesigner.ExampleModelHasElements> GetLinks( global::BrainTec.NHibernateDesigner.ExampleModel source, global::BrainTec.NHibernateDesigner.ExampleElement target )
		{
			global::System.Collections.Generic.List<global::BrainTec.NHibernateDesigner.ExampleModelHasElements> outLinks = new global::System.Collections.Generic.List<global::BrainTec.NHibernateDesigner.ExampleModelHasElements>();
			global::System.Collections.Generic.IList<global::BrainTec.NHibernateDesigner.ExampleModelHasElements> links = DslModeling::DomainRoleInfo.GetElementLinks<global::BrainTec.NHibernateDesigner.ExampleModelHasElements>(source, global::BrainTec.NHibernateDesigner.ExampleModelHasElements.ExampleModelDomainRoleId);
			foreach ( global::BrainTec.NHibernateDesigner.ExampleModelHasElements link in links )
			{
				if ( target.Equals(link.Element) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one ExampleModelHasElements link between a given ExampleModeland a ExampleElement.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::BrainTec.NHibernateDesigner.ExampleModelHasElements GetLink( global::BrainTec.NHibernateDesigner.ExampleModel source, global::BrainTec.NHibernateDesigner.ExampleElement target )
		{
			global::System.Collections.Generic.IList<global::BrainTec.NHibernateDesigner.ExampleModelHasElements> links = DslModeling::DomainRoleInfo.GetElementLinks<global::BrainTec.NHibernateDesigner.ExampleModelHasElements>(source, global::BrainTec.NHibernateDesigner.ExampleModelHasElements.ExampleModelDomainRoleId);
			foreach ( global::BrainTec.NHibernateDesigner.ExampleModelHasElements link in links )
			{
				if ( target.Equals(link.Element) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
namespace BrainTec.NHibernateDesigner
{
	/// <summary>
	/// DomainRelationship ExampleElementReferencesTargets
	/// Reference relationship between Elements.
	/// </summary>
	[DslDesign::DisplayNameResource("BrainTec.NHibernateDesigner.ExampleElementReferencesTargets.DisplayName", typeof(global::BrainTec.NHibernateDesigner.NHibernateDesignerDomainModel), "BrainTec.NHibernateDesigner.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("BrainTec.NHibernateDesigner.ExampleElementReferencesTargets.Description", typeof(global::BrainTec.NHibernateDesigner.NHibernateDesignerDomainModel), "BrainTec.NHibernateDesigner.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::BrainTec.NHibernateDesigner.NHibernateDesignerDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship()]
	[DslModeling::DomainObjectId("9e9bb806-8140-497d-9191-3e2883012972")]
	public partial class ExampleElementReferencesTargets : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// ExampleElementReferencesTargets domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x9e9bb806, 0x8140, 0x497d, 0x91, 0x91, 0x3e, 0x28, 0x83, 0x01, 0x29, 0x72);
	
				
		/// <summary>
		/// Constructor
		/// Creates a ExampleElementReferencesTargets link in the same Partition as the given ExampleElement
		/// </summary>
		/// <param name="source">ExampleElement to use as the source of the relationship.</param>
		/// <param name="target">ExampleElement to use as the target of the relationship.</param>
		public ExampleElementReferencesTargets(ExampleElement source, ExampleElement target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(ExampleElementReferencesTargets.SourceDomainRoleId, source), new DslModeling::RoleAssignment(ExampleElementReferencesTargets.TargetDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public ExampleElementReferencesTargets(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public ExampleElementReferencesTargets(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public ExampleElementReferencesTargets(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public ExampleElementReferencesTargets(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region Source domain role code
		
		/// <summary>
		/// Source domain role Id.
		/// </summary>
		public static readonly global::System.Guid SourceDomainRoleId = new global::System.Guid(0x99b67e94, 0xa56c, 0x4966, 0xa0, 0x2b, 0xb2, 0xdd, 0x0d, 0xea, 0xf6, 0xb3);
		
		/// <summary>
		/// DomainRole Source
		/// Description for BrainTec.NHibernateDesigner.ExampleRelationship.Target
		/// </summary>
		[DslDesign::DisplayNameResource("BrainTec.NHibernateDesigner.ExampleElementReferencesTargets/Source.DisplayName", typeof(global::BrainTec.NHibernateDesigner.NHibernateDesignerDomainModel), "BrainTec.NHibernateDesigner.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("BrainTec.NHibernateDesigner.ExampleElementReferencesTargets/Source.Description", typeof(global::BrainTec.NHibernateDesigner.NHibernateDesignerDomainModel), "BrainTec.NHibernateDesigner.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "Targets", PropertyDisplayNameKey="BrainTec.NHibernateDesigner.ExampleElementReferencesTargets/Source.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("99b67e94-a56c-4966-a02b-b2dd0deaf6b3")]
		public virtual ExampleElement Source
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (ExampleElement)DslModeling::DomainRoleInfo.GetRolePlayer(this, SourceDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, SourceDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Sources of a ExampleElement
		/// <summary>
		/// Gets a list of Sources.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<ExampleElement> GetSources(ExampleElement element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<ExampleElement>, ExampleElement>(element, TargetDomainRoleId);
		}
		#endregion
		#region Target domain role code
		
		/// <summary>
		/// Target domain role Id.
		/// </summary>
		public static readonly global::System.Guid TargetDomainRoleId = new global::System.Guid(0x9166e6e1, 0x3f92, 0x4e7f, 0xaa, 0xc5, 0x62, 0x7c, 0x3c, 0x71, 0xaa, 0x58);
		
		/// <summary>
		/// DomainRole Target
		/// Description for BrainTec.NHibernateDesigner.ExampleRelationship.Source
		/// </summary>
		[DslDesign::DisplayNameResource("BrainTec.NHibernateDesigner.ExampleElementReferencesTargets/Target.DisplayName", typeof(global::BrainTec.NHibernateDesigner.NHibernateDesignerDomainModel), "BrainTec.NHibernateDesigner.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("BrainTec.NHibernateDesigner.ExampleElementReferencesTargets/Target.Description", typeof(global::BrainTec.NHibernateDesigner.NHibernateDesignerDomainModel), "BrainTec.NHibernateDesigner.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "Sources", PropertyDisplayNameKey="BrainTec.NHibernateDesigner.ExampleElementReferencesTargets/Target.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("9166e6e1-3f92-4e7f-aac5-627c3c71aa58")]
		public virtual ExampleElement Target
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (ExampleElement)DslModeling::DomainRoleInfo.GetRolePlayer(this, TargetDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, TargetDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Targets of a ExampleElement
		/// <summary>
		/// Gets a list of Targets.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<ExampleElement> GetTargets(ExampleElement element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<ExampleElement>, ExampleElement>(element, SourceDomainRoleId);
		}
		#endregion
		#region Source link accessor
		/// <summary>
		/// Get the list of ExampleElementReferencesTargets links to a ExampleElement.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::BrainTec.NHibernateDesigner.ExampleElementReferencesTargets> GetLinksToTargets ( global::BrainTec.NHibernateDesigner.ExampleElement sourceInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::BrainTec.NHibernateDesigner.ExampleElementReferencesTargets>(sourceInstance, global::BrainTec.NHibernateDesigner.ExampleElementReferencesTargets.SourceDomainRoleId);
		}
		#endregion
		#region Target link accessor
		/// <summary>
		/// Get the list of ExampleElementReferencesTargets links to a ExampleElement.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::BrainTec.NHibernateDesigner.ExampleElementReferencesTargets> GetLinksToSources ( global::BrainTec.NHibernateDesigner.ExampleElement targetInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::BrainTec.NHibernateDesigner.ExampleElementReferencesTargets>(targetInstance, global::BrainTec.NHibernateDesigner.ExampleElementReferencesTargets.TargetDomainRoleId);
		}
		#endregion
		#region ExampleElementReferencesTargets instance accessors
		
		/// <summary>
		/// Get any ExampleElementReferencesTargets links between a given ExampleElement and a ExampleElement.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::BrainTec.NHibernateDesigner.ExampleElementReferencesTargets> GetLinks( global::BrainTec.NHibernateDesigner.ExampleElement source, global::BrainTec.NHibernateDesigner.ExampleElement target )
		{
			global::System.Collections.Generic.List<global::BrainTec.NHibernateDesigner.ExampleElementReferencesTargets> outLinks = new global::System.Collections.Generic.List<global::BrainTec.NHibernateDesigner.ExampleElementReferencesTargets>();
			global::System.Collections.Generic.IList<global::BrainTec.NHibernateDesigner.ExampleElementReferencesTargets> links = DslModeling::DomainRoleInfo.GetElementLinks<global::BrainTec.NHibernateDesigner.ExampleElementReferencesTargets>(source, global::BrainTec.NHibernateDesigner.ExampleElementReferencesTargets.SourceDomainRoleId);
			foreach ( global::BrainTec.NHibernateDesigner.ExampleElementReferencesTargets link in links )
			{
				if ( target.Equals(link.Target) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one ExampleElementReferencesTargets link between a given ExampleElementand a ExampleElement.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::BrainTec.NHibernateDesigner.ExampleElementReferencesTargets GetLink( global::BrainTec.NHibernateDesigner.ExampleElement source, global::BrainTec.NHibernateDesigner.ExampleElement target )
		{
			global::System.Collections.Generic.IList<global::BrainTec.NHibernateDesigner.ExampleElementReferencesTargets> links = DslModeling::DomainRoleInfo.GetElementLinks<global::BrainTec.NHibernateDesigner.ExampleElementReferencesTargets>(source, global::BrainTec.NHibernateDesigner.ExampleElementReferencesTargets.SourceDomainRoleId);
			foreach ( global::BrainTec.NHibernateDesigner.ExampleElementReferencesTargets link in links )
			{
				if ( target.Equals(link.Target) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
