//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrainTec.NHibernateDesigner
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "nh";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"NHibernateDesigner";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"BrainTec";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID NHibernateDesignerDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(NHibernateDesignerCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID NHibernateDesignerExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(NHibernateDesignerCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewNHibernateDesignerExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(NHibernateDesignerCommandSetId), 0x0001);
	
		// Package identifier
		public const string NHibernateDesignerPackageId = "3f2f1297-ae09-4f92-823b-d267afd64139";
		
		// Editor factory identifier
		public const string NHibernateDesignerEditorFactoryId = "133f388c-2bde-4615-947b-623fff388837";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string NHibernateDesignerModelExplorerToolWindowId = "9c55708b-bdd0-4b7b-85a9-de86e318efe6";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace BrainTec.NHibernateDesigner
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string NHibernateDesignerCommandSetId = "dafaddd5-8ba0-40f2-bb3a-b2984a9e6094";
	}
}